/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DreamverseRouteImport } from './routes/dreamverse'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HeroverseRouteImport } from './routes/heroverse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MovieMovieIdRouteImport } from './routes/movie.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamverseRoute = DreamverseRouteImport.update({
  id: '/dreamverse',
  path: '/dreamverse',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroverseRoute = HeroverseRouteImport.update({
  id: '/heroverse',
  path: '/heroverse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdRoute = MovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dreamverse': typeof DreamverseRoute
  '/favorites': typeof FavoritesRoute
  '/heroverse': typeof HeroverseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/universe': typeof UniverseRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dreamverse': typeof DreamverseRoute
  '/favorites': typeof FavoritesRoute
  '/heroverse': typeof HeroverseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/universe': typeof UniverseRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dreamverse': typeof DreamverseRoute
  '/favorites': typeof FavoritesRoute
  '/heroverse': typeof HeroverseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/universe': typeof UniverseRoute
  '/watchlist': typeof WatchlistRoute
  '/movie/$movieId': typeof MovieMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dreamverse'
    | '/favorites'
    | '/heroverse'
    | '/login'
    | '/profile'
    | '/signup'
    | '/universe'
    | '/watchlist'
    | '/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dreamverse'
    | '/favorites'
    | '/heroverse'
    | '/login'
    | '/profile'
    | '/signup'
    | '/universe'
    | '/watchlist'
    | '/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/dreamverse'
    | '/favorites'
    | '/heroverse'
    | '/login'
    | '/profile'
    | '/signup'
    | '/universe'
    | '/watchlist'
    | '/movie/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DreamverseRoute: typeof DreamverseRoute
  FavoritesRoute: typeof FavoritesRoute
  HeroverseRoute: typeof HeroverseRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  UniverseRoute: typeof UniverseRoute
  WatchlistRoute: typeof WatchlistRoute
  MovieMovieIdRoute: typeof MovieMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreamverse': {
      id: '/dreamverse'
      path: '/dreamverse'
      fullPath: '/dreamverse'
      preLoaderRoute: typeof DreamverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroverse': {
      id: '/heroverse'
      path: '/heroverse'
      fullPath: '/heroverse'
      preLoaderRoute: typeof HeroverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId': {
      id: '/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DreamverseRoute: DreamverseRoute,
  FavoritesRoute: FavoritesRoute,
  HeroverseRoute: HeroverseRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  UniverseRoute: UniverseRoute,
  WatchlistRoute: WatchlistRoute,
  MovieMovieIdRoute: MovieMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
